### ISSUE TITLE
ETH 2.0 Meeting Oct 29th / Same day as EthMagicians?

### ISSUE THREAD

**Issue by bmann** [ethresearch/eth2.0-pm#7]
Hello! I've heard that Oct 29th is a tentative date for meeting ahead of DevCon4, which is the same day as the EthMagicians Council.

Any way we can connect / overlap the two?

**Comment by djrtwo** [comment]
Hi! 

I actually turned down the opportunity to schedule our event in the same venue as the Council as to not detract/distract from the magicians. I am realizing now that I might have done the opposite or at least missed the opportunity for some positive overlap.

Can we schedule a call to discuss the two events and how we might collaborate on the 29th or sometime during that week in Prague?

**Comment by bmann** [comment]
Thanks @djrtwo, got you on email now with Lane.
